# Generated by Django 4.1.7 on 2023-03-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pColor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
